import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@components/components/Layout/Header";

const inter = Inter({ subsets: ["latin"] });

const layoutStyles = {
  margin: '20px',
}

const navLinks = [
  { href: '/', label: 'Home' },
  { href: '/portfolio', label: 'Portfolio' },
  { href: '/contact', label: 'Contact Me' },
]

export const metadata: Metadata = {
  title: "Default Title",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body style={layoutStyles} className={inter.className}>
        <Header navLinks={navLinks}/>
        {children}
      </body>
    </html>
  );
}
